### ISSUE TITLE
Youtube thumnbnails not including timestamps in link. 

### ISSUE THREAD

**Issue by Koonboi** [klinker-apps/pulse-sms-issues#964] opened 2020-02-10 14:34 UTC
*Please read my notes, then replace my notes to fill in this template with your own information and check the boxes to confirm you understand the report that you are filing.*

## Confirm this Issue

- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [X] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [X] I have verified that this is something that is reproducible.
- [X] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Device/Platform Information

**Device with issue:** Linux Desktop running v4.0.1 and Pixel 3 
**Primary device:** Pixel 3 on Android 10
**App version:** v5.1.1.2706

## Describe the Bug

When sending youtube links with a timestamp, such as `https://youtu.be/[random]?t=668` the video thumbnail inserted by pulse does not include the timestamp. Clicking the thumbnail or video title takes you to the start of the video instead. I can still click the text link that was sent to get to the correct part of the video. 

### Steps to Reproduce

1. Share youtube link including timestamp.
2. Click on the generated preview.
3. Watch video start at the beginning.

### Expected Behavior

The video should start at the selected time no matter where I click. 

### Screenshots

N/A

### Additional Information
N/A

**Comment by klinker24** [comment] 2020-02-10 14:47
This is due to the way [`article-android`](https://github.com/klinker41/article-android) handles url parameters and will be solved with that library

Duplicate of #550

**Closed by klinker24** 2020-02-10 14:47 UTC
