### ISSUE TITLE
Pin/lock messages in a conversation

### ISSUE THREAD

**Issue by Enn83** [klinker-apps/pulse-sms-issues#954] opened 2020-01-15 21:17 UTC
## Confirm this Issue
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.
- [x] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

I confirm I've check online and on github and I don't find a topic like this.

## Describe Your Request

It would be usefull to pin/lock messages in a conversation, eventually to prevent from deleting if I delete all the conversation, or a multi-selection of messages, and find them easily.
To find them easily, eventualy add an option/button like for scheduled messages (a new icon appears left to the attachment icon), or like in Discord (for pinned messages).

**Comment by klinker24** [comment] 2020-01-15 21:35
Duplicate of #136.

**Closed by klinker24** 2020-01-15 21:35 UTC
