### ISSUE TITLE
GIF picker support in desktop app

### ISSUE THREAD

**Issue by coolhand33** [klinker-apps/pulse-sms-issues#981] opened 2020-04-03 16:20 UTC
*Please read my notes, then replace my notes to fill in this template with your own information and check the boxes to confirm you understand the request.*

## Confirm this Issue

- [X ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [X ] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.
- [ X] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Describe Your Request

The ability to select from a GIF picker within the native desktop app.

### Describe alternatives you've considered

You can attach a GIF with the file attachment feature, but that is very clunky and less UX friendly.  A duplicate of the feature within the mobile app would be better.

### Additional information

Use the GIF keyboard on android.  Replicate that in the desktop app.  Easier said than done, but would be a welcomed feature.

**Comment by Yosh23** [comment] 2020-04-03 16:32
I second this request. It would be a very welcomed feature

**Comment by klinker24** [comment] 2020-04-03 16:35
Duplicate of #625

**Closed by klinker24** 2020-04-03 16:35 UTC
