### ISSUE TITLE
Auto enable/disable driving mode

### ISSUE THREAD

**Issue by KevRomine** [klinker-apps/pulse-sms-issues#992] opened 2020-05-12 00:33 UTC
The ability to automatically switch driving mode by sensing BT or WiFi would be a very helpful feature.

In my case I'm in and out of the car multiple times a day and I only remember to switch it about half the time.

**Comment by klinker24** [comment] 2020-05-12 00:35
Duplicate of #673

**Closed by klinker24** 2020-05-12 00:35 UTC
